export const VIT_LOCATIONS = [
  { id: "main-gate", label: "Main Gate", category: "Gates & Hotspots" },
  { id: "anc-gate", label: "ANC Gate", category: "Gates & Hotspots" },
  { id: "gate-3", label: "Gate 3", category: "Gates & Hotspots" },
  { id: "food-court", label: "Food Court (FC)", category: "Gates & Hotspots" },
  { id: "enzo", label: "Enzo", category: "Gates & Hotspots" },
  { id: "sjt", label: "SJT (Silver Jubilee Tower)", category: "Academic Blocks" },
  { id: "tt", label: "TT (Technology Tower)", category: "Academic Blocks" },
  { id: "smv", label: "SMV", category: "Academic Blocks" },
  { id: "mb", label: "Main Building (MB)", category: "Academic Blocks" },
  { id: "cdmm", label: "CDMM", category: "Academic Blocks" },
  { id: "mh-a", label: "Men's Hostel - A Block", category: "Men's Hostels" },
  { id: "mh-b", label: "Men's Hostel - B Block", category: "Men's Hostels" },
  { id: "mh-c", label: "Men's Hostel - C Block", category: "Men's Hostels" },
  { id: "mh-d", label: "Men's Hostel - D Block", category: "Men's Hostels" },
  { id: "mh-e", label: "Men's Hostel - E Block", category: "Men's Hostels" },
  { id: "mh-f", label: "Men's Hostel - F Block", category: "Men's Hostels" },
  { id: "mh-g", label: "Men's Hostel - G Block", category: "Men's Hostels" },
  { id: "mh-h", label: "Men's Hostel - H Block", category: "Men's Hostels" },
  { id: "mh-j", label: "Men's Hostel - J Block", category: "Men's Hostels" },
  { id: "mh-k", label: "Men's Hostel - K Block", category: "Men's Hostels" },
  { id: "mh-l", label: "Men's Hostel - L Block", category: "Men's Hostels" },
  { id: "mh-m", label: "Men's Hostel - M Block", category: "Men's Hostels" },
  { id: "mh-n", label: "Men's Hostel - N Block", category: "Men's Hostels" },
  { id: "mh-p", label: "Men's Hostel - P Block", category: "Men's Hostels" },
  { id: "mh-q", label: "Men's Hostel - Q Block", category: "Men's Hostels" },
  { id: "mh-r", label: "Men's Hostel - R Block", category: "Men's Hostels" },
  { id: "mh-t", label: "Men's Hostel - T Block", category: "Men's Hostels" },
  { id: "wh-a", label: "Women's Hostel - A Block", category: "Women's Hostels" },
  { id: "wh-b", label: "Women's Hostel - B Block", category: "Women's Hostels" },
  { id: "wh-c", label: "Women's Hostel - C Block", category: "Women's Hostels" },
  { id: "wh-d", label: "Women's Hostel - D Block", category: "Women's Hostels" },
  { id: "wh-e", label: "Women's Hostel - E Block", category: "Women's Hostels" },
  { id: "wh-f", label: "Women's Hostel - F Block", category: "Women's Hostels" },
  { id: "wh-g", label: "Women's Hostel - G Block", category: "Women's Hostels" },
  { id: "wh-h", label: "Women's Hostel - H Block", category: "Women's Hostels" },
  { id: "wh-j", label: "Women's Hostel - J Block", category: "Women's Hostels" },
  { id: "wh-s", label: "Women's Hostel - S Block", category: "Women's Hostels" }
];
